namespace: apkawa
name: collection_template
version: 0.0.1
readme: README.md
authors:
  - Apkawa <apkawa@gmail.com>

description: ansible collection template
license:
  - WTFPL

tags: [ ]

dependencies: { }
repository: https://github.com/Apkawa/ansible-collection-template
documentation: https://github.com/Apkawa/ansible-collection-template/README.md
homepage: https://github.com/Apkawa/ansible-collection-template
issues: https://github.com/Apkawa/ansible-collection-template/issues
