---

- name: Create a directory if it does not exist
  ansible.builtin.file:
    path: /tmp/test
    state: touch
    mode: '0644'

- name: Ensure test file
  ansible.builtin.lineinfile:
    path: /tmp/test
    regexp: '^EXAMPLE='
    line: EXAMPLE=molecule
