name: Test collection

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  changelog:
    uses: Apkawa/github-actions/.github/workflows/ansible_collections-changelog.yml@master
  integration:
    uses: Apkawa/github-actions/.github/workflows/ansible_collections-integration_simple.yml@master
  sanity:
    uses: Apkawa/github-actions/.github/workflows/ansible_collections-sanity.yml@master
  unit-galaxy:
    uses: Apkawa/github-actions/.github/workflows/ansible_collections-unit_galaxy.yml@master

  all_green:
    if: ${{ always() }}
    needs:
      - changelog
      - integration
      - sanity
      - unit-galaxy
    runs-on: ubuntu-latest
    steps:
      - run: >-
          python -c "assert set([
          '${{ needs.changelog.result }}',
          '${{ needs.integration.result }}',
          '${{ needs.sanity.result }}',
          '${{ needs.unit-galaxy.result }}'
          ]) == {'success'}"
